### ISSUE TITLE
fails on ES6 modules with dynamic imports

### ISSUE THREAD

**Issue by dgoldstein0** [buxlabs/amd-to-es6#109]
in https://github.com/piuccio/rollup-plugin-amd/issues/17 I discovered that, when es6 modules are run through this plugin, dynamic `import()` calls cause parsing to fail.  Likely this is because we need to pass a newer `ecmaVersion` to acorn, so it'll parse according to the new standard instead of the old one.  This might also require upgrading acorn.  Potentially it would just make sense to pass a higher ecmaVersion to acorn in this project, but if not exposing the acorn options to the consumer would also work.

**Comment by emilos** [comment]
hey @dgoldstein0 thanks for the report. I'll take a look later today

**Comment by dgoldstein0** [comment]
any updates?

**Comment by emilos** [comment]
@dgoldstein0 sorry for the late reply! 

I've investigated the issue and:
- updated cherow to 1.6.8
- turned on the next flag to support the dynamic import
- tested a bit and saw that estraverse does not support dynamic imports yet

given the fact that estraverse is not actively maintained I've come up with a different solution that should be "good enough" (I hope) for now.

Before any ast manipulation: `import(` is replaced with `DYNAMIC_IMPORT_PLACEHOLDER(`
After source/map generation: `DYNAMIC_IMPORT_PLACEHOLDER(` is replaced with `import(`

It's definitely not perfect but otherwise you'd probably need to wait much longer.

Please try the version `@buxlabs/amd-to-es6@0.13.1` and let me know if that helped.

**Comment by dgoldstein0** [comment]
Oh fun, I actually ran into the same estraverse bug in one of my scripts, and reported it upstream: https://github.com/estools/estraverse/issues/97.  My workaround was actually a lot simpler: the crash happens when traversing into the children of the import node, so for my purposes skipping traversing into import nodes worked well - which was just a well-placed `this.skip()`; more details in my upstream report.

anyhow, thanks for this fix!
